Fix url rewrite
codeday-labs/bookworms pull request #13
Opened 2021-07-13 04:58 UTC by auroravo2001

fixed URL rewrite when switching between 2 pages on remote env. - used basename in BrowserRouter (https://reactrouter.com/web/api/BrowserRouter/basename-string)

2021-07-13 07:27 UTC, jeromewu requested changes
Overall comments:

1. Next time I think it is better to create a new branch to fix url rewrite instead of mixing it with `homepage-feed` branch, it makes this PR more clear and easy to merge.
2. Instead of putting all the CSS style in `index.css`, it is more recommended to use a css module, you can check more details here: [Adding Stylesheets](https://create-react-app.dev/docs/adding-a-stylesheet) and [BEM](https://medium.com/seek-blog/block-element-modifying-your-javascript-components-d7f99fcab52b)
3. In common practice, it is not recommended to commit .DS_Store file, please help to exclude / delete them using gitignore, ref: https://stackoverflow.com/questions/18393498/gitignore-all-the-ds-store-files-in-every-folder-and-subfolder

2021-07-13 07:27 UTC, jeromewu commented on client/src/ReviewList.js
> +                    </div>
A better way to write this component:

```javascript
// destructure reviews from props directly
function ReviewList ({ reviews }) {

    const [fav, setFav] = useState(false);
   // func name start with a verb
    const toggleFavorite = () => {
      setFav(!fav)
    };

   // select component using shorthand if else
   const FavIcon = fav ? FavoriteIcon : FavoriteBorderIcon;

    return (
        <div className="review-list">
            {reviews.map((r) => (
                <div className="review-preview" key={r.id}>
                    <h1> {r.bookname} </h1>
                    <h2> Published by {r.name} </h2>
                    <p> {r.body} </p>
                    <div className="footer">
                        <p> {r.categories} </p>
                        <FavIcon
                          className="footer-right"
                          onClick={toggleFavorite}
                        />
                    </div>
                </div>
            ))}
        </div>
    );
}
```

2021-07-13 07:27 UTC, jeromewu commented on client/src/favoriteButton.js
> +ReactDOM.render(<LikeButton />, document.getElementById('root'));
Should export this component instead of render.

2021-07-13 07:27 UTC, jeromewu commented on client/src/favoriteButton.js
> +class LikeButton extends React.Component {
Better to write this as functional component instead of class component to be consistent.

2021-07-14 07:27 UTC, auroravo2001 commented
I tried remove DS.Store in all directories manually via terminal and it seems to disappear on the branches, so hopefully, it will ignore DS.Store from now on when I commit something...!

2021-07-14 08:56 UTC, auroravo2001 commented
I am still trying out how and where to display the filter for category [still currently working on it] -- but the homepage version that was pushed as of now is an okay version (not 100% functional but the idea is there). Would you mind look it over and see if it works for now? @jeromewu

2021-07-14 08:59 UTC, jeromewu commented
OK, let's not to include filter in this PR to be more agile, I will start the code review now.

2021-07-14 11:10 UTC, jeromewu requested changes
Instead of `tools/`, most of the time people name that folder `components/` to indicate that they are components that might be reused. It is recommended to use that.

Other than that, only 1 review comment left. :smile:

2021-07-14 11:10 UTC, jeromewu commented on client/src/tools/SearchBar.js
> +                className={styles.inputArea && styles.searchTerm}
For variable like `styles.inputArea`, the value is actually a string (you can console.log to check), so in JavaScript when you use AND operator with strings, it returns the last string:

```java
const s1 = 'foo';
const s2 = 'bar';

console.log(s1 && s2); // bar
```
Which I think is not the purpose of this line of code

2021-07-14 12:37 UTC, auroravo2001 commented
Sorry for the late notification!

2021-07-14 12:48 UTC, jeromewu approved these changes

2021-07-14 12:48 UTC, jeromewu commented
Thanks for the hard work, it is merged now. :tada:

2021-07-14 12:48 UTC, merged